version: '3.1'

services:
  nginx:
    image: mynginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/ssl:/etc/letsencrypt
      - ./logs/nginx/:/var/log/nginx
    environment:
      - TZ=Europe/Kiev